### ISSUE TITLE
Document the dependency on OSX CoreAudio

### ISSUE THREAD

**Issue by llogiq** [yupferris/samurai-pizza-cats#46]
This doesn't even compile under Linux or Windows. The README doesn't even mention the dependency.

**Comment by yupferris** [comment]
Thanks for the report, but I believe the readme _does_ mention the dependency?

"Note: Due to current limitations in the emu project on which this depends, this will only build on OS X. Other platforms will be supported promptly."

It's the second paragraph under the "Description" section.

**Comment by yupferris** [comment]
![screen shot 2015-10-26 at 10 59 33 am](https://cloud.githubusercontent.com/assets/3166056/10737680/cf05d536-7bd0-11e5-94a7-048ae13bc1d2.png)

**Comment by yupferris** [comment]
The dependency has been made a dev-dependency for now in https://github.com/emu-rs/snes-apu/commit/92e73bf990a4bacf99fdfec4011f43895aba43f6, as the audio driver abstractions were only actually necessary to build the example. The rest of the code should build on other platforms just fine.

I'll update the text in the readme to reflect that the example currently only supports OS X, and close this.
